### PR TITLE
Write to cloudwatch

### PR DESCRIPTION
**Pull request by davebally**

### CODE REVIEW

**Comment by mattjmatthias** [comment]
Thanks Dave, appreciated :)

**Comment by davebally** [comment]
No worries, hope it makes sense....  The credentials can be replaced with ECSTaskCredentials if you are having problems or just dont set Credentials and it should default to Env variables / config file

**Comment by mattjmatthias** [comment]
It does, and when I run that locally and provide my temp AWS credentials it logs to dbTest, but nowhere else. When I send that up to AWS EC2 and run it there nothing goes into a log and it dies. I've tried no credentials, and again no logs and death. I'm beginning to wonder if I'm sending something up from Windows like an errant CRLF which is upsetting something.

**Comment by davebally** [comment]
I wouldn’t have thought so…  If you put in wrong creds to the logging,  it just fails silently ,  it wont barf.

Are you getting nothing at all in the stopped tasks logs ?
The console.writeline should go there at least.

**Comment by mattjmatthias** [comment]
Not a sausage, nothing in the task logs, nothing in cloudwatch. I've half given up on the output to STNDOUT on asp net core, assuming it's blocked by design without config. I added a console out in Nlog 
`<target xsi:type="Console" name="lifetimeConsole" layout="${MicrosoftConsoleLayout}" />`
but it didn't send anything to ECS task log. 

I noticed in that in the ECSFargetTest you put together for me, the log messages in the app appeared in Cloudwatch but not the task logs. No log messages from the app appeared in task logs.

**Comment by davebally** [comment]
OK, you could try using logmonitor….

Streaming logs from Amazon EKS Windows pods to Amazon CloudWatch Logs using Fluentd | Containers<https://aws.amazon.com/blogs/containers/streaming-logs-from-amazon-eks-windows-pods-to-amazon-cloudwatch-logs-using-fluentd/>

Can you send me the task json, see if I can spot anything

**Comment by mattjmatthias** [comment]
Thanks, I'll check it out. Here's the task definition being used:

```
{
    "taskDefinitionArn": "arn:aws:ecs:eu-west-2:307494535005:task-definition/TaskEcsNetTestAwsLogging:7",
    "containerDefinitions": [
        {
            "name": "ecsnettestawslogging",
            "image": "307494535005.dkr.ecr.eu-west-2.amazonaws.com/ecsnettestawslogging:1.1",
            "cpu": 0,
            "links": [],
            "portMappings": [
                {
                    "name": "ecsnettestawslogging-80-tcp",
                    "containerPort": 80,
                    "hostPort": 80,
                    "protocol": "tcp",
                    "appProtocol": "http"
                }
            ],
            "essential": true,
            "entryPoint": [],
            "command": [],
            "environment": [
                {
                    "name": "Test",
                    "value": "Matt"
                }
            ],
            "environmentFiles": [],
            "mountPoints": [],
            "volumesFrom": [],
            "secrets": [],
            "dnsServers": [],
            "dnsSearchDomains": [],
            "extraHosts": [],
            "dockerSecurityOptions": [],
            "dockerLabels": {},
            "ulimits": [],
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-create-group": "true",
                    "awslogs-group": "/ecs/TaskEcsNetTestAwsLogging",
                    "awslogs-region": "eu-west-2",
                    "awslogs-stream-prefix": "ecs"
                },
                "secretOptions": []
            },
            "systemControls": []
        }
    ],
    "family": "TaskEcsNetTestAwsLogging",
    "executionRoleArn": "arn:aws:iam::307494535005:role/ecsTaskExecutionRole",
    "networkMode": "awsvpc",
    "revision": 7,
    "volumes": [],
    "status": "ACTIVE",
    "requiresAttributes": [
        {
            "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
        },
        {
            "name": "ecs.capability.execution-role-awslogs"
        },
        {
            "name": "com.amazonaws.ecs.capability.ecr-auth"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.17"
        },
        {
            "name": "ecs.capability.execution-role-ecr-pull"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
        },
        {
            "name": "ecs.capability.task-eni"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.29"
        }
    ],
    "placementConstraints": [],
    "compatibilities": [
        "EC2",
        "FARGATE"
    ],
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "cpu": "1024",
    "memory": "3072",
    "runtimePlatform": {
        "cpuArchitecture": "X86_64",
        "operatingSystemFamily": "LINUX"
    },
    "registeredAt": "2022-12-02T16:08:14.732Z",
    "registeredBy": "arn:aws:sts::307494535005:assumed-role/AWSReservedSSO_AdministratorAccess_ae7cff79993a5114/mmatthias@evoraglobal.com",
    "tags": [
        {
            "key": "ecs:taskDefinition:createdFrom",
            "value": "ecs-console-v2"
        },
        {
            "key": "ecs:taskDefinition:stackId",
            "value": "arn:aws:cloudformation:eu-west-2:307494535005:stack/ECS-Console-V2-TaskDefinition-cbac8045-2f0f-40b3-8c3c-cd5ed5841bea/b11c1e30-7255-11ed-b7c5-0657f9c99216"
        }
    ]
}
```

**Comment by davebally** [comment]
Hmm, cant see anything in particular …

Have you checked the cloudTrail logs ?  User the taskId as the username to search..

And have you had anything running at all with .Net ?
Event the step by step examples ?? Hosting ASP.NET Core applications in Amazon ECS using AWS Fargate | AWS Compute Blog<https://aws.amazon.com/blogs/compute/hosting-asp-net-core-applications-in-amazon-ecs-using-aws-fargate/>

**Comment by davebally** [comment]
Hi Matt,

Hmm,  ive pushed my own version up and all seems fine…   18.198.26.145<http://18.198.26.145/>
I get logs, cloudwatch etc….

My task definition is :

{
    "compatibilities": [
        "EC2",
        "FARGATE"
    ],
    "containerDefinitions": [
        {
            "command": [
            ],
            "cpu": 0,
            "dependsOn": null,
            "disableNetworking": null,
            "dnsSearchDomains": null,
            "dnsServers": null,
            "dockerLabels": null,
            "dockerSecurityOptions": null,
            "entryPoint": [
            ],
            "environment": [
            ],
            "environmentFiles": null,
            "essential": true,
            "extraHosts": null,
            "firelensConfiguration": null,
            "healthCheck": null,
            "hostname": null,
            "image": "877366120527.dkr.ecr.eu-central-1.amazonaws.com/dbtester:latest",
            "interactive": null,
            "links": null,
            "linuxParameters": null,
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-group": "/ecs/dbTester",
                    "awslogs-region": "eu-central-1",
                    "awslogs-stream-prefix": "ecs"
                },
                "secretOptions": null
            },
            "memory": null,
            "memoryReservation": null,
            "mountPoints": [
            ],
            "name": "dbtester",
            "portMappings": [
                {
                    "containerPort": 80,
                    "hostPort": 80,
                    "protocol": "tcp"
                },
                {
                    "containerPort": 443,
                    "hostPort": 443,
                    "protocol": "tcp"
                }
            ],
            "privileged": null,
            "pseudoTerminal": null,
            "readonlyRootFilesystem": null,
            "resourceRequirements": null,
            "secrets": null,
            "startTimeout": null,
            "stopTimeout": null,
            "systemControls": null,
            "ulimits": null,
            "user": null,
            "volumesFrom": [
            ],
            "workingDirectory": null
        }
    ],
    "cpu": "1024",
    "executionRoleArn": "arn:aws:iam::877366120527:role/ecsTaskExecutionRole",
    "family": "dbTester",
    "inferenceAccelerators": null,
    "ipcMode": null,
    "memory": "3072",
    "networkMode": "awsvpc",
    "pidMode": null,
    "placementConstraints": [
    ],
    "proxyConfiguration": null,
    "requiresAttributes": [
        {
            "name": "com.amazonaws.ecs.capability.logging-driver.awslogs",
            "targetId": null,
            "targetType": null,
            "value": null
        },
        {
            "name": "ecs.capability.execution-role-awslogs",
            "targetId": null,
            "targetType": null,
            "value": null
        },
        {
            "name": "com.amazonaws.ecs.capability.ecr-auth",
            "targetId": null,
            "targetType": null,
            "value": null
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19",
            "targetId": null,
            "targetType": null,
            "value": null
        },
        {
            "name": "com.amazonaws.ecs.capability.task-iam-role",
            "targetId": null,
            "targetType": null,
            "value": null
        },
        {
            "name": "ecs.capability.execution-role-ecr-pull",
            "targetId": null,
            "targetType": null,
            "value": null
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18",
            "targetId": null,
            "targetType": null,
            "value": null
        },
        {
            "name": "ecs.capability.task-eni",
            "targetId": null,
            "targetType": null,
            "value": null
        }
    ],
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "revision": 1,
    "runtimePlatform": {
        "cpuArchitecture": null,
        "operatingSystemFamily": "LINUX"
    },
    "status": "ACTIVE",
    "taskDefinitionArn": "arn:aws:ecs:eu-central-1:877366120527:task-definition/dbTester:1",
    "taskRoleArn": "arn:aws:iam::877366120527:role/ecsTaskExecutionRole",
    "volumes": [
    ]
}


Diffing the two,  the most significant is you have cpuArchitecture as X86_64 where as mine is null !
I

**Comment by davebally** [comment]
Happy to have a quick zoom to see if we can debug.



From: Dave Ballantyne
Sent: 05 December 2022 10:28
To: mattjmatthias/EcsNetTestAwsLogging ***@***.***>; mattjmatthias/EcsNetTestAwsLogging ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [mattjmatthias/EcsNetTestAwsLogging] Write to cloudwatch (PR #1)

Hi Matt,

Hmm,  ive pushed my own version up and all seems fine…   18.198.26.145<http://18.198.26.145/>
I get logs, cloudwatch etc….

My task definition is :

{
    "compatibilities": [
        "EC2",
        "FARGATE"
    ],
    "containerDefinitions": [
        {
            "command": [
            ],
            "cpu": 0,
            "dependsOn": null,
            "disableNetworking": null,
            "dnsSearchDomains": null,
            "dnsServers": null,
            "dockerLabels": null,
            "dockerSecurityOptions": null,
            "entryPoint": [
            ],
            "environment": [
            ],
            "environmentFiles": null,
            "essential": true,
            "extraHosts": null,
            "firelensConfiguration": null,
            "healthCheck": null,
            "hostname": null,
            "image": "877366120527.dkr.ecr.eu-central-1.amazonaws.com/dbtester:latest",
            "interactive": null,
            "links": null,
            "linuxParameters": null,
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-group": "/ecs/dbTester",
                    "awslogs-region": "eu-central-1",
                    "awslogs-stream-prefix": "ecs"
                },
                "secretOptions": null
            },
            "memory": null,
            "memoryReservation": null,
            "mountPoints": [
            ],
            "name": "dbtester",
            "portMappings": [
                {
                    "containerPort": 80,
                    "hostPort": 80,
                    "protocol": "tcp"
                },
                {
                    "containerPort": 443,
                    "hostPort": 443,
                    "protocol": "tcp"
                }
            ],
            "privileged": null,
            "pseudoTerminal": null,
            "readonlyRootFilesystem": null,
            "resourceRequirements": null,
            "secrets": null,
            "startTimeout": null,
            "stopTimeout": null,
            "systemControls": null,
            "ulimits": null,
            "user": null,
            "volumesFrom": [
            ],
            "workingDirectory": null
        }
    ],
    "cpu": "1024",
    "executionRoleArn": "arn:aws:iam::877366120527:role/ecsTaskExecutionRole",
    "family": "dbTester",
    "inferenceAccelerators": null,
    "ipcMode": null,
    "memory": "3072",
    "networkMode": "awsvpc",
    "pidMode": null,
    "placementConstraints": [
    ],
    "proxyConfiguration": null,
    "requiresAttributes": [
        {
            "name": "com.amazonaws.ecs.capability.logging-driver.awslogs",
            "targetId": null,
            "targetType": null,
            "value": null
        },
        {
            "name": "ecs.capability.execution-role-awslogs",
            "targetId": null,
            "targetType": null,
            "value": null
        },
        {
            "name": "com.amazonaws.ecs.capability.ecr-auth",
            "targetId": null,
            "targetType": null,
            "value": null
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19",
            "targetId": null,
            "targetType": null,
            "value": null
        },
        {
            "name": "com.amazonaws.ecs.capability.task-iam-role",
            "targetId": null,
            "targetType": null,
            "value": null
        },
        {
            "name": "ecs.capability.execution-role-ecr-pull",
            "targetId": null,
            "targetType": null,
            "value": null
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18",
            "targetId": null,
            "targetType": null,
            "value": null
        },
        {
            "name": "ecs.capability.task-eni",
            "targetId": null,
            "targetType": null,
            "value": null
        }
    ],
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "revision": 1,
    "runtimePlatform": {
        "cpuArchitecture": null,
        "operatingSystemFamily": "LINUX"
    },
    "status": "ACTIVE",
    "taskDefinitionArn": "arn:aws:ecs:eu-central-1:877366120527:task-definition/dbTester:1",
    "taskRoleArn": "arn:aws:iam::877366120527:role/ecsTaskExecutionRole",
    "volumes": [
    ]
}


Diffing the two,  the most significant is you have cpuArchitecture as X86_64 where as mine is null !
I

**Comment by mattjmatthias** [comment]
Sure, will a teams meeting link for work you?

https://teams.microsoft.com/l/meetup-join/19%3Ameeting_ZWI1YTRmNGItMzJhNi00MDQ0LTllYjEtZDQzODBlYWIwNWIw%40thread.v2/0?context=%7B%22Tid%22%3A%22da002c52-917a-4b5f-a723-4baa5fdd4874%22%2C%22Oid%22%3A%22acc8e70a-1592-4740-9368-d6d02d2d8c65%22%2C%22MessageId%22%3A%220%22%7D 

I'll be in there for the next 30 mins then I've got to dash off for a bit.

**Comment by davebally** [comment]
Image is here…

https://1drv.ms/u/s!Aix-iLyjtgRAhJJRj0OPfx3OWiQSBA?e=LR2n3m

Couldnt push as I need explicit permission to push which makes sense.

You can use docker load, then push.

**Pull request merged**
